// 7 categories total: Exercise & Study are from the reference design,
// the remaining 5 are original additions in the same card style.
export const categories = [
  {
    id: "exercise",
    label: "Exercise",
    count: 4,
    icon: "barbell-outline",
    bg: "accentCoralSoft",
    fg: "accentCoral",
  },
  {
    id: "study",
    label: "Study",
    count: 6,
    icon: "book-outline",
    bg: "primarySoft",
    fg: "primary",
  },
  {
    id: "work",
    label: "Work",
    count: 5,
    icon: "briefcase-outline",
    bg: "accentBlueSoft",
    fg: "accentBlue",
  },
  {
    id: "reading",
    label: "Reading",
    count: 3,
    icon: "reader-outline",
    bg: "accentYellowSoft",
    fg: "accentYellow",
  },
  {
    id: "meditation",
    label: "Meditation",
    count: 2,
    icon: "leaf-outline",
    bg: "accentMintSoft",
    fg: "accentMint",
  },
  {
    id: "coding",
    label: "Coding",
    count: 7,
    icon: "code-slash-outline",
    bg: "primarySoft",
    fg: "primaryDark",
  },
  {
    id: "design",
    label: "Design",
    count: 4,
    icon: "color-palette-outline",
    bg: "accentPinkSoft",
    fg: "accentPink",
  },
];
