// 8 ongoing tasks total: Mobile App Development, Web Development, and
// Push Ups are from the reference design, the remaining 5 are original
// additions in the same card style.
export const tasks = [
  {
    id: "mobile-app-dev",
    title: "Mobile App Development",
    category: "Coding",
    due: "Today, 5:00 PM",
    progress: 0.65,
    icon: "phone-portrait-outline",
    bg: "primarySoft",
    fg: "primary",
  },
  {
    id: "web-dev",
    title: "Web Development",
    category: "Coding",
    due: "Tomorrow, 10:00 AM",
    progress: 0.4,
    icon: "globe-outline",
    bg: "accentBlueSoft",
    fg: "accentBlue",
  },
  {
    id: "push-ups",
    title: "Push Ups",
    category: "Exercise",
    due: "Today, 6:00 AM",
    progress: 0.8,
    icon: "barbell-outline",
    bg: "accentCoralSoft",
    fg: "accentCoral",
  },
  {
    id: "uiux-wireframes",
    title: "UI/UX Wireframes",
    category: "Design",
    due: "Wed, 2:00 PM",
    progress: 0.5,
    icon: "color-palette-outline",
    bg: "accentPinkSoft",
    fg: "accentPink",
  },
  {
    id: "data-structures",
    title: "Data Structures Assignment",
    category: "Study",
    due: "Fri, 11:59 PM",
    progress: 0.3,
    icon: "book-outline",
    bg: "accentYellowSoft",
    fg: "accentYellow",
  },
  {
    id: "morning-yoga",
    title: "Morning Yoga Flow",
    category: "Meditation",
    due: "Today, 7:00 AM",
    progress: 0.9,
    icon: "leaf-outline",
    bg: "accentMintSoft",
    fg: "accentMint",
  },
  {
    id: "quarterly-report",
    title: "Quarterly Report",
    category: "Work",
    due: "Mon, 9:00 AM",
    progress: 0.2,
    icon: "briefcase-outline",
    bg: "accentBlueSoft",
    fg: "accentBlue",
  },
  {
    id: "chapter-reading",
    title: "Chapter 5 Reading",
    category: "Reading",
    due: "Today, 9:00 PM",
    progress: 0.55,
    icon: "reader-outline",
    bg: "primarySoft",
    fg: "primaryDark",
  },
];
